Add README.md and package.json for example packages
DataSQRL/datasqrl-examples pull request #26
Opened 2024-09-30 21:08 UTC by nandorsoma

2024-10-01 17:42 UTC, Zesky665 approved these changes

2024-10-08 03:13 UTC, mbroecheler requested changes
Thanks a lot for this very thorough update and documentation. My one minor concern is that duplicating an entire SQRL script and GraphQL schema into the documentation will be hard to maintain. If we need to update the source files, we would have to remember to update the README. I propose that we instead link to those files. That's slightly less convenient for the user, but much easier to maintain moving forward. WDYT?

2024-10-08 22:10 UTC, nandorsoma commented
> Thanks a lot for this very thorough update and documentation. My one minor concern is that duplicating an entire SQRL script and GraphQL schema into the documentation will be hard to maintain. If we need to update the source files, we would have to remember to update the README. I propose that we instead link to those files. That's slightly less convenient for the user, but much easier to maintain moving forward. WDYT?

I agree with your point and had the same thought. However, I believe it’s crucial to prioritize user convenience. Sometimes, saving a click can significantly enhance their experience, especially when navigating a document like this one. What if we embedded other README files into this document, similar to using an <iframe> in HTML. Fortunately docusaurus allows for similar functionality: https://docusaurus.io/docs/markdown-features/react#importing-markdown

One downside is that, in a few cases (maybe just one), I had to adjust the script slightly to fit the example packages. I’m unsure how to address this, but it might be lower on our priority list.

What do you think?

2024-10-08 22:50 UTC, mbroecheler commented
I agree with you that having the full example in the documentation (without having to link elsewhere) is what we want. I think the iframe idea is a neat why to accomplish that without duplicating code.
However, this PR is about the documentation of the packages in the repository. That's where these readme's are embedded and there we want to link to the repository or datasqrl-examples. I don't think the repository should turn into another source of documentation beyond what is in the actual packages.

2024-10-10 16:51 UTC, mbroecheler approved these changes

2024-10-11 08:34 UTC, merged