Add tests to the datasqrl-examples repo
DataSQRL/datasqrl-examples pull request #30
Opened 2024-10-14 16:11 UTC by Zesky665

I updated the build pipeline to include tests for each of the examples and I also added a manual run option. 

Once the PR is merged, anyone with the ability to run GitHub Actions on the repo will be able to use it to run tests on one of the examples by using the `Run Workflow` button.
<img width="1213" alt="image" src="https://github.com/user-attachments/assets/4aaca78d-7b10-4c91-a1f4-0316a9053703">

2024-10-14 16:13 UTC, Zesky665 commented
Do you guys think that adding an option for running all of the tests is warranted?

2024-10-15 16:04 UTC, henneberger requested changes

2024-10-15 16:04 UTC, henneberger commented on .github/workflows/build-config.yml
> +      run: docker pull datasqrl/sqrl-demo:latest
Lets move back to cmd:v0.5.6. The sqrl-demo will be removed soon.

2024-10-15 16:07 UTC, Zesky665 commented on .github/workflows/build-config.yml
> +      run: docker pull datasqrl/sqrl-demo:latest
Good catch, I'm on it.

2024-10-15 16:12 UTC, Zesky665 commented on .github/workflows/build-config.yml
> +      run: docker pull datasqrl/sqrl-demo:latest
Done

2024-10-15 16:22 UTC, merged